[package]
name = "repo"
version = "0.1.0"
edition = "2024"

[dependencies]
data = { path = "data" }
service = { path = "service" }

iced = { version = "0.13.1", features = ["tokio", "lazy"] }

[workspace]
resolver = "2"
members = ["data", "service"]
